apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: null
  labels:
    app: mongodb-replicaset
    chart: mongodb-replicaset-3.9.2
    heritage: Tiller
    release: mongodb
  name: mongodb-mongodb-replicaset
  selfLink: /api/v1/namespaces/default/services/mongodb-mongodb-replicaset
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  publishNotReadyAddresses: true
  selector:
    app: mongodb-replicaset
    release: mongodb
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: "35.240.100.78"
status:
  loadBalancer: {}

