apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongodb
    chart: mongodb-5.14.2
    heritage: Tiller
    release: mongodb
  name: mongodb
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: default
